version: '3.8'

services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: 'spring-reviewer-db-local'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "frozzel"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "reviewers"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frozzel -d reviewers"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: 'spring-reviewer-backend-local'
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/reviewers
      DATABASE_USER: frozzel
      DATABASE_PASSWORD: 12345
      # Убеждаемся, что эта строка точно есть и без опечаток
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/my-reviewer-ui
      dockerfile: Dockerfile.frontend
    container_name: 'spring-reviewer-frontend-local'
    ports:
      - "5173:80"
    environment:
      # Убеждаемся, что эта переменная задана
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data: