version: '3'
services:
    db:
        image: postgres:13
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=frozzel
            - POSTGRES_DB=reviewer
            - POSTGRES_PASSWORD=12345
            - PGDATA=/var/lib/postgresql/data/pgdata
