spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewers?stringtype=unspecified
    username: frozzel
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    name: logs/application.log
generated:
  logs:
    dir: ./generated-logs
springdoc:
  api-docs:
    path: /api-docs
    info:
      title: Teacher Review API
      version: v1.0.0
      description: API для управления отзывами о преподавателях
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha